CREATE TABLE ATC ( 
  ATC_ID INTEGER PRIMARY KEY, 
  CODE VARCHAR(7) NULL, 
  WARNDUPLICATES BOOLEAN 
);
CREATE TABLE ATC_LABELS ( 
  ATC_ID        integer not null, 
  MASTER_LID    integer not null, 
  UNIQUE(ATC_ID, MASTER_LID), 
  FOREIGN KEY(ATC_ID) REFERENCES ATC(ATC_ID), 
  FOREIGN KEY(MASTER_LID) REFERENCES LABELS_LINK(MASTER_LID) 
);
CREATE TABLE BIBLIOGRAPHY ( 
  BIB_ID    INTEGER PRIMARY KEY, 
  TYPE      varchar(20), 
  LINK      varchar(200), 
  TEXTUAL_REFERENCE varchar(1000), 
  ABSTRACT  varchar(4000), 
  EXPLANATION varchar(4000) 
);
CREATE TABLE BIBLIOGRAPHY_LINKS ( 
  BIB_MASTER_ID integer, 
  BIB_ID        integer, 
  UNIQUE(BIB_MASTER_ID, BIB_ID), 
  FOREIGN KEY(BIB_ID) REFERENCES BIBLIOGRAPHY(BIB_ID) 
);
CREATE TABLE COMPOSITION ( 
  DID           integer not null, 
  MID           integer not null, 
  STRENGTH      varchar(150), 
  STRENGTH_NID  integer, 
  DOSE_REF      varchar(150), 
  DOSE_REF_NID  integer, 
  NATURE        varchar(2), 
  LK_NATURE     integer, 
  FOREIGN KEY(DID) REFERENCES MASTER(DID), 
  FOREIGN KEY(MID) REFERENCES MOLS(MID) 
);
CREATE TABLE DB_SCHEMA_VERSION ( 
  ID INTEGER NOT NULL  PRIMARY KEY, 
  VERSION varchar(10), 
  DATE  date, 
  COMMENT varchar(500) 
);
CREATE TABLE DRUGS ( 
  ID        INTEGER NOT NULL PRIMARY KEY, 
  DID       integer, 
  SID       integer, 
  NAME      varchar(255), 
  ATC_ID    integer, 
  STRENGTH  varchar(40), 
  VALID     boolean, 
  MARKETED  boolean, 
  AID_MASTER_LID  integer, 
  LINK_SPC  varchar(500), 
  EXTRA_XML varchar(5000), 
  FOREIGN KEY(DID) REFERENCES MASTER(DID) 
);
CREATE TABLE DRUG_FORMS ( 
  DID           integer not null, 
  MASTER_LID    integer not null, 
  UNIQUE(DID,MASTER_LID), 
  FOREIGN KEY(DID) REFERENCES MASTER(DID), 
  FOREIGN KEY(MASTER_LID) REFERENCES LABELS_LINK(MASTER_LID) 
);
CREATE TABLE DRUG_ROUTES ( 
  DID  integer not null, 
  RID  integer not null, 
  UNIQUE(DID,RID), 
  FOREIGN KEY(DID) REFERENCES MASTER(DID), 
  FOREIGN KEY(RID) REFERENCES ROUTES(RID) 
);
CREATE TABLE IAFORMALIZED ( 
  IAFID               INTEGER PRIMARY KEY, 
  BLEEDINGSCORE       integer, 
  RENALFAILSCORE      integer, 
  PULMFAILSCORE       integer, 
  HEPATICFAILSCORE    integer, 
  HEARTFAILSCORE      integer, 
  HEARTRYTHMFAILSCORE integer, 
  MAINDOSEFROM        varchar(25), 
  MAINDOSETO          varchar(25), 
  IDOSEFROM           varchar(25), 
  IDOSETO             varchar(25), 
  MAINROUTE           integer, 
  INTERACTORROUTE     integer, 
  MAINADESCORE        integer, 
  IADESCORE           integer 
);
CREATE TABLE IAKNOWLEDGE ( 
  IAKID               INTEGER PRIMARY KEY, 
  TYPE                varchar(5), 
  RISK_MASTER_LID     integer, 
  MAN_MASTER_LID      integer, 
  BIB_MASTER_ID       integer, 
  WWW                 varchar(100), 
  FOREIGN KEY(RISK_MASTER_LID) REFERENCES LABELS_LINK(MASTER_LID), 
  FOREIGN KEY(MAN_MASTER_LID) REFERENCES LABELS_LINK(MASTER_LID), 
  FOREIGN KEY(BIB_MASTER_ID) REFERENCES BIBLIOGRAPHY_LINKS(BIB_MASTER_ID) 
);
CREATE TABLE IAM_TREE ( 
  ID_CLASS       integer not null, 
  ID_ATC         integer not null, 
  BIB_MASTER_ID  integer default -1, 
  FOREIGN KEY(ID_CLASS) REFERENCES ATC(ATC_ID), 
  FOREIGN KEY(ID_ATC) REFERENCES ATC(ATC_ID), 
  FOREIGN KEY(BIB_MASTER_ID) REFERENCES BIBLIOGRAPHY_LINKS(BIB_MASTER_ID) 
);
CREATE TABLE IA_IAK ( 
  IAID   integer not null, 
  IAKID  integer not null, 
  UNIQUE(IAID, IAKID), 
  FOREIGN KEY(IAID) REFERENCES INTERACTIONS(IAID), 
  FOREIGN KEY(IAKID) REFERENCES IAKNOWLEDGE(IAKID) 
 );
CREATE TABLE INTERACTIONS ( 
  IAID INTEGER PRIMARY KEY, 
  ATC_ID1 integer not null, 
  ATC_ID2 integer not null, 
  FOREIGN KEY(ATC_ID1) REFERENCES ATC(ATC_ID), 
  FOREIGN KEY(ATC_ID2) REFERENCES ATC(ATC_ID) 
 );
CREATE TABLE LABELS ( 
  LID   INTEGER PRIMARY KEY, 
  LANG  varchar(5), 
  LABEL varchar(250) 
);
CREATE TABLE LABELS_LINK ( 
  MASTER_LID    integer not null, 
  LID           integer not null, 
  UNIQUE(MASTER_LID, LID), 
  FOREIGN KEY(LID) REFERENCES LABELS(LID) 
);
CREATE TABLE LK_MOL_ATC ( 
  MID     integer not null, 
  ATC_ID  integer not null, 
  SID     integer not null, 
  UNIQUE(MID,ATC_ID,SID) 
);
CREATE TABLE MASTER ( 
  DID      INTEGER PRIMARY KEY, 
  UID1     varchar(50) not null, 
  UID2     varchar(50), 
  UID3     varchar(50), 
  OLD_UID  varchar(50), 
  SID      integer 
);
CREATE TABLE MOLS ( 
  MID       INTEGER PRIMARY KEY, 
  SID       integer, 
  NAME      varchar(150), 
  WWW       varchar(200) 
);
CREATE TABLE PACKAGING ( 
  DID integer not null, 
  SID integer, 
  PACKAGE_UID int(20) NOT NULL, 
  LABEL varchar(500) NOT NULL, 
  STATUS varchar(1), 
  MARKETING int(1) NOT NULL DEFAULT 1, 
  DATE varchar(25), 
  OPTIONAL_CODE int(20) 
);
CREATE TABLE PIMS ( 
  PIM_ID          INTEGER PRIMARY KEY, 
  PIM_SID         integer, 
  PIM_TID         integer, 
  LEVEL           integer, 
  RISK_MASTER_LID integer, 
  FOREIGN KEY(PIM_SID) REFERENCES PIM_SOURCES(PIM_SID), 
  FOREIGN KEY(PIM_TID) REFERENCES PIM_TYPES(PIM_TID) 
);
CREATE TABLE PIMS_RELATED_ATC ( 
  PIM_RMID         INTEGER PRIMARY KEY, 
  PIM_ID           integer, 
  ATC_ID           integer, 
  MAXDAYDOSE       double, 
  MAXDAYDOSEUNIT   integer, 
  FOREIGN KEY(PIM_ID) REFERENCES PIMS(PIM_ID), 
  FOREIGN KEY(ATC_ID) REFERENCES ATC(ATC_ID) 
);
CREATE TABLE PIMS_RELATED_ICD ( 
  PIM_RMID         INTEGER PRIMARY KEY, 
  PIM_ID           integer, 
  ICD10_ID         integer, 
  FOREIGN KEY(PIM_ID) REFERENCES PIMS(PIM_ID) 
);
CREATE TABLE PIM_SOURCES ( 
  PIM_SID        INTEGER PRIMARY KEY, 
  UID            varchar(50), 
  NAME           varchar(255), 
  PMID           integer, 
  COUNTRY        varchar(20), 
  WWW            varchar(500) 
);
CREATE TABLE PIM_TYPES ( 
  PIM_TID        INTEGER PRIMARY KEY, 
  UID            varchar(50), 
  MASTER_LID     integer, 
  FOREIGN KEY(MASTER_LID) REFERENCES LABELS_LINK(MASTER_LID) 
);
CREATE TABLE ROUTES ( 
  RID           INTEGER PRIMARY KEY, 
  MASTER_LID    integer not null, 
  IS_SYSTEMIC   integer, 
  UNIQUE(RID, MASTER_LID), 
  FOREIGN KEY(MASTER_LID) REFERENCES LABELS_LINK(MASTER_LID) 
);
CREATE TABLE SEARCH_ENGINES ( 
  ID integer NOT NULL  primary key, 
  LABEL varchar(25), 
  URL varchar(1000) 
);
CREATE TABLE SOURCES ( 
  SID             INTEGER PRIMARY KEY, 
  DATABASE_UID    varchar(20) not null, 
  MASTER_LID      integer, 
  LANG            varchar(5), 
  WEB             varchar(250), 
  COPYRIGHT       varchar(500), 
  DATE            date, 
  DRUGS_VERSION   varchar(10), 
  AUTHORS         varchar(200), 
  VERSION         varchar(10), 
  PROVIDER        varchar(200), 
  WEBLINK         varchar(500), 
  DRUG_UID_NAME   varchar(50), 
  ATC             bool default true, 
  INTERACTIONS    bool default true, 
  COMPLEMENTARY_WEBSITE  varchar(200), 
  PACK_MAIN_CODE_NAME    varchar(50), 
  MOL_LINK_COMPLETION    integer default 0, 
  AUTHOR_COMMENTS        varchar(10000), 
  DRUGS_NAME_CONSTRUCTOR varchar(200), 
  FREEMEDFORMS_COMPTA_VERSION varchar(10), 
  WEBPORTAL_COMPTA_VERSION    varchar(10) 
);
CREATE TABLE UNITS ( 
  NID     INTEGER PRIMARY KEY, 
  VALUE   varchar(20) 
);
CREATE INDEX AtcCodePk ON ATC (CODE);
CREATE INDEX AtcIndexPk ON ATC (ATC_ID);
CREATE INDEX AtcLabelsK ON ATC_LABELS (ATC_ID, MASTER_LID);
CREATE INDEX AtcTreeClassK ON IAM_TREE (ID_CLASS,ID_ATC,BIB_MASTER_ID);
CREATE INDEX BibLinksMasterK ON BIBLIOGRAPHY_LINKS (BIB_MASTER_ID,BIB_ID);
CREATE INDEX BibsIndexPk ON BIBLIOGRAPHY (BIB_ID);
CREATE INDEX CompoDrugIndexPk ON  COMPOSITION (DID);
CREATE INDEX CompoMolsIndexPk ON  COMPOSITION (MID);
CREATE INDEX DrugRoutesDidFk ON DRUG_ROUTES (DID,RID);
CREATE INDEX DrugsFormsK ON DRUG_FORMS (DID,MASTER_LID);
CREATE INDEX DrugsIndexPk ON DRUGS (DID);
CREATE INDEX IaAtcId1Fk ON INTERACTIONS (ATC_ID1,ATC_ID2);
CREATE INDEX IaFIndexPk ON IAFORMALIZED (IAFID);
CREATE INDEX IaIndexPk ON INTERACTIONS (IAID);
CREATE INDEX IaToIakK ON IA_IAK (IAID,IAKID);
CREATE INDEX IakIndexPk ON IAKNOWLEDGE (IAKID,RISK_MASTER_LID,MAN_MASTER_LID,BIB_MASTER_ID);
CREATE INDEX LabelsIndexPk ON LABELS (LID);
CREATE INDEX LabelsLinkK ON LABELS_LINK (MASTER_LID,LID);
CREATE INDEX LkMolAtcK ON LK_MOL_ATC (MID,ATC_ID,SID);
CREATE INDEX MasterIndexPk ON MASTER (DID);
CREATE INDEX MolsIndexPk ON MOLS (MID);
CREATE INDEX PimSourceIndex ON PIM_SOURCES (PIM_SID);
CREATE INDEX PimTypesIndex ON PIM_TYPES (PIM_TID);
CREATE INDEX PimsAtcAtcIdIndex ON PIMS_RELATED_ATC (ATC_ID);
CREATE INDEX PimsAtcIndex ON PIMS_RELATED_ATC (PIM_RMID);
CREATE INDEX PimsAtcPimIdIndex ON PIMS_RELATED_ATC (PIM_ID);
CREATE INDEX PimsIcdAtcIdIndex ON PIMS_RELATED_ICD (ICD10_ID);
CREATE INDEX PimsIcdIndex ON PIMS_RELATED_ICD (PIM_RMID);
CREATE INDEX PimsIcdPimIdIndex ON PIMS_RELATED_ICD (PIM_ID);
CREATE INDEX PimsIndex ON PIMS (PIM_ID);
CREATE INDEX RoutesK ON ROUTES (RID, MASTER_LID);
CREATE INDEX UnitsIndexPk ON UNITS (NID);
